import type { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = (process.env.NEXT_PUBLIC_APP_URL || 'https://executivemochi.pk').replace(/\/$/, '');

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/shop',
          '/product/',
          '/about',
          '/craftsmanship',
          '/stores',
          '/size-guide',
          '/contact',
          '/faqs',
          '/shipping',
          '/returns',
          '/privacy',
          '/terms',
          '/careers',
          '/llms.txt',
          '/llms-full.txt',
          '/api/images/',
          '/api/gmc/feed',
        ],
        disallow: [
          '/admin',
          '/admin/',
          '/branch',
          '/branch/',
          '/account',
          '/account/',
          '/checkout',
          '/checkout/',
          '/order-success',
          '/order-success/',
          '/cart',
          '/cart/',
          '/wishlist',
          '/wishlist/',
          '/api/trpc/',
          '/api/auth/',
          '/api/upload',
          '/api/webhooks/',
        ],
      },
      // Google Search Central
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/shop',
          '/product/',
          '/about',
          '/craftsmanship',
          '/stores',
          '/size-guide',
          '/contact',
          '/faqs',
          '/shipping',
          '/returns',
          '/privacy',
          '/terms',
          '/careers',
          '/llms.txt',
          '/llms-full.txt',
          '/api/gmc/feed',
          '/api/images/',
        ],
        disallow: [
          '/admin',
          '/admin/',
          '/branch',
          '/branch/',
          '/account',
          '/account/',
          '/checkout',
          '/checkout/',
          '/order-success',
          '/order-success/',
          '/cart',
          '/cart/',
          '/wishlist',
          '/wishlist/',
          '/api/trpc/',
        ],
      },
      // Bing Webmaster Tools
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/shop',
          '/product/',
          '/about',
          '/craftsmanship',
          '/stores',
          '/size-guide',
          '/contact',
          '/faqs',
          '/shipping',
          '/returns',
          '/privacy',
          '/terms',
          '/careers',
          '/llms.txt',
          '/llms-full.txt',
          '/api/gmc/feed',
          '/api/images/',
        ],
        disallow: [
          '/admin',
          '/admin/',
          '/branch',
          '/branch/',
          '/account',
          '/account/',
          '/checkout',
          '/checkout/',
          '/order-success',
          '/order-success/',
          '/cart',
          '/cart/',
          '/wishlist',
          '/wishlist/',
          '/api/trpc/',
        ],
      },
      // Generative AI / LLM search bots (GEO optimization)
      {
        userAgent: [
          'GPTBot',
          'ChatGPT-User',
          'PerplexityBot',
          'ClaudeBot',
          'anthropic-ai',
          'Google-Extended',
          'Applebot',
        ],
        allow: [
          '/',
          '/shop',
          '/product/',
          '/about',
          '/craftsmanship',
          '/size-guide',
          '/stores',
          '/llms.txt',
          '/llms-full.txt',
          '/api/images/',
        ],
        disallow: [
          '/admin',
          '/admin/',
          '/branch',
          '/branch/',
          '/account',
          '/account/',
          '/checkout',
          '/cart',
          '/api/',
        ],
      },
      // Image Crawlers
      {
        userAgent: 'Googlebot-Image',
        allow: ['/', '/api/images/', '/images/', '/*.jpg', '/*.jpeg', '/*.png', '/*.webp', '/*.avif'],
        disallow: ['/admin', '/admin/', '/branch', '/branch/'],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
